constructor {
  New : ();
};

service TransferCall {
  CreateVft : (code_id: code_id, name: str, symbol: str, decimals: u8) -> bool;
  Transfer : (token: actor_id, to: actor_id, value: u256) -> bool;
  TransferFrom : (token: actor_id, from: actor_id, to: actor_id, value: u256) -> bool;
  query GetBalanceFromContract : (owner: actor_id, token: actor_id) -> u256;

  events {
    Transfer: struct { vft: actor_id, from: actor_id, to: actor_id, value: u256 };
    VftCreated: struct { vft: actor_id, name: str, symbol: str, decimals: u8 };
  }
};

